export const partnershipCrmSeed = [
  {
    slug: "dxo", company: "DxO", category: "Editing software", stage: "Contacted", score: 96, valueCents: 12_500_000,
    website: "https://www.dxo.com", contact: "Partnership team", role: "Business development",
    nextStep: "Follow up on direct publishing integration",
    summary: "A premium editing ecosystem with a highly engaged photographer audience and a natural need for a stronger presentation and publishing destination.",
    opportunity: "Create a direct PhotoView publishing destination from DxO applications so finished images can become cinematic galleries, portfolios, and coordinated social campaigns.",
    painPoints: ["Finished images leave the DxO ecosystem", "Users still need separate portfolio and gallery software", "Publishing and social presentation are fragmented"],
    integration: ["Export selected images directly to PhotoView", "Create or update a gallery during export", "Preserve metadata and captions", "Offer a co-marketed extended trial"],
    activities: [
      { displayDate: "Jul 19", title: "Initial partnership outreach", detail: "Introduced the direct publishing concept and PhotoView positioning.", type: "email" },
      { displayDate: "Jul 18", title: "Company dossier completed", detail: "Mapped product fit, user overlap, and likely integration value.", type: "research" },
    ],
  },
  {
    slug: "topaz-labs", company: "Topaz Labs", category: "AI imaging", stage: "Research", score: 94, valueCents: 11_000_000,
    website: "https://www.topazlabs.com", contact: "Ross Shain", role: "Principal Creative Technologist", linkedin: "https://www.linkedin.com/in/rossshain/",
    nextStep: "Personalize outreach around export workflow",
    summary: "Topaz helps photographers improve image quality with AI. PhotoView can become the immediate destination where those improved images are presented and promoted.",
    opportunity: "Position PhotoView as the post-enhancement presentation layer after Topaz Photo AI and adjacent Topaz workflows.",
    painPoints: ["The workflow ends after image enhancement", "Users must manually move to portfolio tools", "No built-in cinematic publishing layer"],
    integration: ["Publish enhanced images to PhotoView", "Launch a new portfolio or gallery", "Generate social-ready campaigns", "Bundle a PhotoView trial for Topaz customers"],
    activities: [{ displayDate: "Jul 20", title: "Contact selected", detail: "Ross Shain identified as the strongest creative technology contact.", type: "research" }],
  },
  {
    slug: "capture-one", company: "Capture One", category: "Editing software", stage: "Contacted", score: 93, valueCents: 15_000_000,
    website: "https://www.captureone.com", contact: "Martin Thorn", role: "Partnership contact",
    nextStep: "Send product demo and integration outline",
    summary: "Capture One serves professional photographers who care deeply about image quality, workflow, and presentation—an excellent audience match for PhotoView.",
    opportunity: "Add PhotoView as a premium publishing endpoint for sessions, albums, and completed edits.",
    painPoints: ["Professional work still needs an external presentation layer", "Client delivery and public portfolio workflows diverge", "Social promotion requires separate tools"],
    integration: ["Publish albums or selections", "Map Capture One metadata to PhotoView", "Create cinematic gallery presets", "Offer professional co-marketing"],
    activities: [{ displayDate: "Jul 19", title: "Outreach sent", detail: "Sent partnership introduction to Martin Thorn.", type: "email" }],
  },
  {
    slug: "on1", company: "ON1", category: "Editing software", stage: "Research", score: 91, valueCents: 9_500_000,
    website: "https://www.on1.com", contact: "Product partnerships", role: "Product team", nextStep: "Identify decision maker and verified email",
    summary: "ON1 combines editing, effects, resizing, and workflow tools for photographers. PhotoView can extend that workflow into presentation and promotion.",
    opportunity: "Offer one-click publishing from ON1 into a cinematic PhotoView gallery and portfolio system.",
    painPoints: ["Publishing is outside the core workflow", "Users juggle separate portfolio services", "No unified presentation and social layer"],
    integration: ["Export to PhotoView", "Create gallery from album", "Preserve keywords and descriptions", "Joint launch campaign"], activities: [],
  },
  {
    slug: "acdsee", company: "ACDSee", category: "Digital asset management", stage: "Research", score: 89, valueCents: 8_000_000,
    website: "https://www.acdsee.com", contact: "Product partnerships", role: "Business development", nextStep: "Build company dossier",
    summary: "ACDSee users already organize and manage large image libraries. PhotoView provides a logical publishing destination for selected finished work.",
    opportunity: "Turn an ACDSee collection or selection into a published PhotoView gallery without leaving the workflow.",
    painPoints: ["Asset management does not solve presentation", "Publishing selections is manual", "Portfolio tools duplicate organization work"],
    integration: ["Publish selected assets", "Sync metadata", "Create named PhotoView collections", "Offer integrated trial onboarding"], activities: [],
  },
  {
    slug: "imagen-ai", company: "Imagen AI", category: "AI editing", stage: "Conversation", score: 88, valueCents: 12_000_000,
    website: "https://imagen-ai.com", contact: "Partnership team", role: "Strategic partnerships", nextStep: "Prepare workflow mockup",
    summary: "Imagen accelerates professional editing. PhotoView can complete the value chain by helping photographers immediately publish and promote completed work.",
    opportunity: "Create a seamless edited-to-published workflow from Imagen into PhotoView.",
    painPoints: ["Fast editing still leads to manual publishing", "Professional users need client and public presentation options", "Social promotion remains disconnected"],
    integration: ["Send completed projects to PhotoView", "Create galleries automatically", "Apply publishing templates", "Launch partner-specific onboarding"], activities: [],
  },
  {
    slug: "aftershoot", company: "Aftershoot", category: "AI culling", stage: "Research", score: 87, valueCents: 9_000_000,
    website: "https://aftershoot.com", contact: "Growth team", role: "Partnerships", nextStep: "Draft personalized introduction",
    summary: "Aftershoot helps photographers move faster through culling and editing. PhotoView extends that speed through the publishing and promotion stage.",
    opportunity: "Connect completed Aftershoot projects to instant PhotoView galleries and social campaigns.",
    painPoints: ["Workflow acceleration stops before publishing", "Client and portfolio presentation remain separate", "Marketing finished work requires more tools"],
    integration: ["Publish completed project", "Create client or public gallery", "Generate social campaign", "Co-market workflow efficiency"], activities: [],
  },
  {
    slug: "evoto", company: "Evoto", category: "AI retouching", stage: "Research", score: 84, valueCents: 7_500_000,
    website: "https://www.evoto.ai", contact: "Business development", role: "Partnerships", nextStep: "Find verified contact route",
    summary: "Evoto focuses on AI portrait retouching. PhotoView offers portrait photographers an elegant way to present and promote the resulting work.",
    opportunity: "Publish retouched portraits directly into branded PhotoView galleries and campaigns.",
    painPoints: ["Retouched work still needs presentation", "Portrait photographers use fragmented delivery tools", "Social promotion is disconnected"],
    integration: ["Publish retouched selections", "Apply portrait gallery templates", "Preserve retouching metadata", "Offer portrait-focused promotion bundle"], activities: [],
  },
  {
    slug: "adobe", company: "Adobe", category: "Creative software", stage: "Research", score: 82, valueCents: 25_000_000,
    website: "https://www.adobe.com", contact: "Lightroom ecosystem", role: "Partner ecosystem", nextStep: "Map Lightroom plugin requirements",
    summary: "Adobe offers the largest potential reach, but requires a more formal ecosystem and plugin strategy.",
    opportunity: "Develop a Lightroom publishing integration that sends finished collections into PhotoView.",
    painPoints: ["Adobe users rely on third-party presentation tools", "Portfolio and social workflows remain fragmented", "Integration approval may be complex"],
    integration: ["Lightroom publish service", "Collection synchronization", "Metadata mapping", "Adobe Marketplace distribution"], activities: [],
  },
] as const
